aedart/athenaeum

packages/Acl/src/Models/Permissions/Group.php, packages/Acl/src/Models/Role.php, tests/Integration/Acl/Models/RoleModelTest.php
PR adds `createWithPermissions()` and `updateWithPermissions()` helper methods to the ACL Role Eloquent model.
=> Improve role operations

packages/Utils/src/Arr.php, tests/Unit/Utils/ArrTest.php
This fixes #47. Solution has become slightly more heavy, but the functionality now works as expected.
=> Fix array to string conversion, in Arr::differenceAssoc

composer.json, packages/Http/Clients/composer.json, tests/Integration/Http/Clients/C1_QueryTest.php
Apparently Guzzle removed several of it's utility helper methods and replaced it with class components. the previous `GuzzleHttp\Psr7\parse_query()` has been replaced with `\GuzzleHttp\Psr7\Query::parse()`.
This appears to have changed in the following [PR](https://github.com/guzzle/guzzle/pull/2712).
In any case, the utility was only used internally for a few tests and not for by the actual package implementation. Thus, this isn't anything serious or breaking. This fixes #49
=> Fix call to parse query

packages/Testing/src/Laravel/ApplicationInitiator.php, packages/Testing/src/Laravel/Database/MigrateProcessor.php
Fix #55
Had to create a custom `MigrateProcessor` to fix the immediate issue. Not the most kind fix, but at least the tests are working as intended again.
=> Fix unable to run migrations in tests

packages/Contracts/src/Redmine/Iterators/ResultsIterator.php, packages/Contracts/src/Redmine/TraversableResults.php, packages/Redmine/src/Pagination/Iterators/ResultsIterator.php, packages/Redmine/src/Pagination/TraversableResults.php, packages/Redmine/src/RedmineApiResource.php, tests/Integration/Redmine/Pagination/TraversableResultsTest.php
Added a new traversable with an iterator that automatically performs API requests, depending on amount of results shown / available in Redmine.
=> Add a way to automatically paginate through available results

CHANGELOG.md, composer.json, ecs.php, packages/Dto/src/Partials/IoCPartial.php, packages/Testing/src/Helpers/ArgumentFaker.php, tests/Integration/Audit/B0_AuditTrailTest.php, tests/Unit/Utils/JsonTest.php, vendor-bin/cs/composer.json
This resolves the relative few PHP `v8.x` compatibility issues that have been identified. Manual execution of all tests has been performed in PHP versions `7.4`, `8.0` and `8.1`.
Additionally, this PR also includes a few vendor-bin dependencies upgrade to phpcs, easy coding standard and PHP-Compatibility (_they proved to be less significant / required than expected_).
Thus, this solves the #61 feature - _at least for now._
=> PHP v8.x compatibility

composer.json, monorepo-builder.php, monorepo-builder.yml, vendor-bin/monorepo/composer.json
Upgraded to [Symplify Monorepo Builder v10.x](https://github.com/symplify/monorepo-builder).
*Note*: _The `split` command is no longer offered, which will require either GitHub Actions or something custom_
=> Migrate to monorepo v10.x

packages/Filters/src/BaseProcessor.php
Now checking if parameter exists inside the received query and obtaining it safely. Method returns `null`, in case that parameter does not exist inside the http query.
#69
=> Fix input value "filter" contains a non-scalar value

packages/Filters/src/BaseProcessor.php
This fixes the side-effect introduced via #70. 
#71
=> Fix Unexpected value for parameter "name": expecting "array"

CHANGELOG.md, docs/archive/current/utils/array.md, docs/archive/current/utils/math.md, packages/Contracts/src/Utils/Clearable.php, packages/Contracts/src/Utils/Populatable.php, packages/Dto/src/Partials/DtoPartial.php, packages/Dto/src/Partials/IoCPartial.php, packages/Http/Clients/src/Requests/Attachment.php, packages/Http/Cookies/src/Cookie.php, packages/Redmine/src/Partials/NestedList.php, packages/Redmine/src/RedmineApiResource.php, packages/Utils/src/Arr.php, packages/Utils/src/Dates/Duration.php, packages/Utils/src/Dates/MicroTimeStamp.php, packages/Utils/src/Helpers/Invoker.php, packages/Utils/src/Helpers/MethodHelper.php, packages/Utils/src/Helpers/PopulateHelper.php, packages/Utils/src/Json.php, packages/Utils/src/Math.php, packages/Utils/src/Str.php, tests/Unit/Utils/ArrTest.php
PR contains various argument and return types improvements. It also contains a major breaking change:
The `populate()` method now returns `static` instead of `void`, in `\Aedart\Contracts\Utils\Populatable` interface.
Lastly, also improved a few docs, such as #45.
=> Improve utils package

CHANGELOG.md, packages/Audit/configs/audit-trail.php, packages/Audit/src/Events/ModelHasChanged.php, packages/Audit/src/Events/MultipleModelsChanged.php, packages/Audit/src/Listeners/RecordAuditTrailEntry.php, packages/Audit/src/Listeners/RecordMultipleAuditTrailEntries.php, packages/Audit/src/Observers/Concerns/ModelChangedEvents.php, packages/Audit/src/Providers/AuditTrailServiceProvider.php, packages/Audit/src/Subscribers/AuditTrailEventSubscriber.php, tests/Integration/Audit/C0_MultipleModelsChangedRecordingTest.php, tests/TestCases/Audit/AuditTestCase.php, tests/_data/configs/audit/audit-trail.php
Adds possibility to record multiple changes, of the same type, for multiple models. E.g. 
* all records have an attribute set to specific value.
* all records are soft-deleted.
* all records are recovered.
Unlike the regular "model has changed" event, this "bulk" operation event must be manually dispatched.
=> Add mass audit trail recording

CHANGELOG.md, packages/Contracts/src/Core/Application.php, packages/Contracts/src/Core/EnvironmentHandler.php, packages/Core/src/Application.php, packages/Testing/src/Athenaeum/ApplicationInitiator.php, tests/Integration/Core/Application/A2_PathsTest.php
The fixes some broken tests, which were unable to detect `APP_ENV`, after it previously was set (_only tests were affected_).
Also, added a new `EnvironmentHandler` interface, which the core `Application` now  inherits from.
=> Adapt env detection and handling

packages/Core/src/Application.php, tests/Integration/Core/Application/A2_PathsTest.php
Since Laravel `v9.x`, the various cache paths util methods have been extracted into separate interfaces. This means that the Core application not longer needs to offer an implementation for these. Furthermore, these were never supported by the Core App.
=> Remove cache related paths

CHANGELOG.md, packages/Contracts/src/Http/Clients/Client.php, packages/Contracts/src/Http/Clients/Requests/Builder.php, packages/Http/Clients/src/Requests/Builders/Concerns/Conditions.php, tests/Integration/Http/Clients/G0_WhenTest.php
Adds support for `callable` results argument for the `when()` and `unless()` method. See #81.
=> Improve when and unless

CHANGELOG.md, docs/archive/current/core/integration.md, packages/Contracts/src/Core/Application.php, packages/Contracts/src/Core/Helpers/PathsContainer.php, packages/Core/helpers/paths.php, packages/Core/src/Application.php, packages/Core/src/Helpers/Paths.php, packages/Testing/src/Athenaeum/ApplicationInitiator.php, tests/Integration/Core/Application/A2_PathsTest.php
Added `langPath()` method to core `Application` and made the `PathsContainer` aware of "lang path".
This is done to be as compatible with Laravel `v9.x` as possible.
See #76
=> Improve core lang

CHANGELOG.md, packages/Dto/src/Partials/CastingPartial.php, packages/Dto/src/Partials/IoCPartial.php, packages/Utils/src/Json.php, tests/Helpers/Dummies/Dto/Article.php, tests/Helpers/Dummies/Dto/Record.php, tests/Integration/Dto/ResolveArrayDtoUnionTypesTest.php, tests/Integration/Dto/ResolveDtoUnionTypesTest.php, tests/TestCases/Dto/DtoTestCase.php, tests/Unit/Utils/JsonTest.php
PR adds support for resolving union type arguments. The `ArrayDto` now also accepts specifying union types in its `$allowed` property.
See #82.
=> Improve Dto and ArrayDto, resolve union types

.github/workflows/split.yaml
Added a "split" workflow which _SHOULD_ replace the previous split. However, it too suffers from not being able to push to the packages' repositories, if the current branch does not exist. The workflow has been set to only activate from the master branch, but has yet to be fully tested / proven.
=> Add split workflow

packages/Audit/src/Events/MultipleModelsChanged.php, packages/Audit/src/Models/Concerns/AuditTrailConfiguration.php, packages/Audit/src/Observers/Concerns/ModelChangedEvents.php, packages/Audit/src/Subscribers/AuditTrailEventSubscriber.php, packages/Audit/src/Traits/RecordsChanges.php
Minor improvements to types in the audit trail package. Also resolved an issues where the PHPDoc claimed to accept an arrya og models, but code excpected an collection of models, in `dispatchMultipleModelsChanged()` method.
See #100
=> Improve types in audit pkg

packages/Core/configs/app.php, tests/_data/configs/maintenance/modes/app.php
Added missing maintenance mode configuration. Also, sets "json" as the default driver.
=> Fix "file" driver not found

CHANGELOG.md, composer.json, monorepo-builder.php, packages/Testing/composer.json, tests/Integration/Flysystem/Db/Adapters/League/DatabaseAdapterTest.php
Codeception or PHPUnit had trouble finding a given test's data provider and started to fail. This fixes the issue, yet not sure why this even is needed...
=> Fix boken db test

.github/workflows/tests.yaml
CI now uses Ubuntu 22.04.
Also, changed the PHP settings to report all errors and added an additional extension, which Laravel also requires
=> Upgrade test environment

packages/Database/src/Models/Concerns/Filtering.php, packages/Filters/src/Processors/ConstraintsProcessor.php, packages/Filters/src/Query/Filters/Fields/BelongsToFilter.php, tests/Helpers/Dummies/Database/Models/Category.php, tests/Helpers/Dummies/Database/Models/Owner.php, tests/Helpers/Dummies/Database/Models/Product.php, tests/Integration/Filters/Relations/RelationsFilteringTest.php
Prevents overwrite of existing filter instance, in the `ConstraintsProcessor`.
A small, but very difficult to spot issue was the main cause of #117. The logical grouping, which was mentioned _should not_ be required at all, because that is automatically handled as intended.
#117
=> Fix filters

CHANGELOG.md, packages/Testing/src/Laravel/Database/TestingConnection.php, tests/TestCases/Acl/AclTestCase.php, tests/TestCases/Audit/AuditTestCase.php, tests/TestCases/Database/DatabaseTestCase.php, tests/TestCases/Flysystem/Db/FlysystemDbTestCase.php, tests/TestCases/Http/ApiResourcesTestCase.php
Fix #123 
Introduced a new `TestingConnection` util that enables a "testing" connection, rather than relying on one being available.
=> Fix driver key not found

CHANGELOG.md, composer.json, packages/Flysystem/Db/composer.json, packages/Flysystem/Db/configs/example-filesystem.php, packages/Flysystem/Db/src/Adapters/Concerns/Hashing.php, packages/Flysystem/Db/src/Adapters/DatabaseAdapter.php, packages/Flysystem/Db/src/Console/MakeAdapterMigrationCommand.php, packages/Flysystem/Db/src/Providers/FlysystemDatabaseAdapterServiceProvider.php, tests/Integration/Flysystem/Db/Adapters/F0_ChecksumTest.php, tests/Integration/Flysystem/Db/Adapters/League/DatabaseAdapterTest.php, tests/Integration/Flysystem/Db/Storage/StorageDiskTest.php
The Flysystem `DatabaseAdapter` has been changed to support League's [checksum](https://flysystem.thephpleague.com/docs/usage/checksums/).
See #121
=> Add support for checksum, in Database Adapter

CHANGELOG.md, packages/ETags/configs/etags.php, packages/ETags/src/Generators/BaseGenerator.php, tests/Integration/Flysystem/Db/Adapters/F0_ChecksumTest.php, tests/Integration/Streams/File/F0_HashingTest.php, tests/_data/configs/etags/etags.php, tests/_data/configs/http/api/etags.php
Change default hashing algorithm to [`xxHash`](https://php.watch/versions/8.1/xxHash) for the etags `BaseGenerator` and example configuration.
=> Change default hashing algorithms to xxHash

CHANGELOG.md, packages/Http/Api/src/Middleware/RemoveResponsePayload.php, tests/Integration/Http/Api/Middleware/RemoveResponsePayloadMiddlewareTest.php
Adds `RemoveResponsePayload` middleware, which is able to convert response to a "204 No Content" response, if a `no_payload` query parameter is requested and the response is successful.
The `no_payload` key can be configured to a different value
=> Add remove payload middleware

CHANGELOG.md, deploy-docs.sh
Minor improvements for the `deploy-docs.sh` script. Ensures that the `.build` directory is cleared, before a new docs build is made.
=> Improve deploy docs script

CHANGELOG.md, docs/archive/current/streams/usage/reading.md, docs/archive/current/streams/usage/writing.md, packages/Contracts/src/Streams/FileStream.php, packages/ETags/src/Preconditions/Responses/DownloadStream.php, packages/Streams/src/Concerns/Buffering.php, packages/Streams/src/Concerns/Copying.php, packages/Streams/src/FileStream.php, packages/Streams/src/Stream.php, tests/Integration/Streams/D5_ReadBufferTest.php, tests/Integration/Streams/File/B0_CopyTest.php
Adds a new `copyFrom()` method in `FileStream`. It is able to safely copy the contents of its source resource or stream into the current stream. It also deals with PSR-7 streams, without detaching its underlying resource.
In addition, a new `buffer()` method has been added in `Stream`, which can read a length of the stream, from an offset and return chunks of data.
See `CHANGELOG.md` for additional details.
* #156
=> Add stream copy from method

CHANGELOG.md, packages/Contracts/src/Validation/FailedState.php, packages/Validation/src/Rules/BaseRule.php, packages/Validation/src/Rules/BaseValidationRule.php, packages/Validation/src/Rules/Concerns/AthenaeumRule.php, packages/Validation/src/Rules/Concerns/Attribute.php, packages/Validation/src/Rules/Concerns/Translations.php, packages/Validation/src/Rules/Concerns/ValidationFailure.php
Deprecation of various validation rule helpers, because of Laravel's deprecated `Rule` interface.
See `CHANGELOG.md`
#158
=> Add base rule replacement

CHANGELOG.md, packages/Http/Api/src/Requests/Resources/ProcessMultipleResourcesRequest.php
PR fixes issue in `ProcessMultipleResourcesRequest`'s applied validation rules. Basically the validation rules were wrapped in a closure, which was never invoked. This resulted in identifiers not being validated at all and could end up being applied / attempted used in the subsequent query.
=> Fix target identifier rules never applied

CHANGELOG.md, packages/Http/Api/src/Requests/ValidatedApiRequest.php
PR fixes the following defect:
* #167 
Sadly, Laravel's feature has now manually been disabled / overwritten, to ensure that the `ApiValidatedRequest` continues to work as intended. Also, a new `afterValidation()` method has been introduced, which replaces the now deprecated `after()` method.
Other Api request abstractions that rely on `after()` have not yet been updated, but that wait until the next major version,...
_See also #168._
=> Fix after validation

CHANGELOG.md, docs/.vuepress/archive/Version7x.ts, docs/archive/current/validation/rules/date-format.md, packages/Filters/src/Query/Filters/Fields/DateFilter.php, packages/Validation/src/Rules/DateFormat.php, tests/Integration/Validation/Rules/DateFormatRuleTest.php, tests/TestCases/Validation/ValidationTestCase.php
PR adds `DateFormat` validation rule, which is able to handle an edge-case that concerns UTC time-zone offset, where the format might use the [`p` token](https://www.php.net/manual/en/datetime.format.php), but the date in question might contain `+00:00` as offset. 
Furthermore, the `DateFilter` and `DateTimeFilter` now use the new validation rule, instead of previous [`date_format`](https://laravel.com/docs/10.x/validation#rule-date-format) rule.
=> Add datetime format validation rule

CHANGELOG.md, packages/Flysystem/Db/src/Adapters/DatabaseAdapter.php, tests/Integration/Flysystem/Db/Adapters/C0_WriteFilesTest.php, tests/Integration/Flysystem/Db/Adapters/D0_FileVisibilityTest.php, tests/Integration/Flysystem/Db/Storage/StorageDiskTest.php, tests/TestCases/Flysystem/Db/FlysystemDbTestCase.php
PR fixes two minor issues with the flyssystem `DatabaseAdapter`:
* `fclose()` was supplied with invalid resource stream when attempting to copy a stream (_affected psql connections_).
* `DatabaseAdapter::createDirectory()` failed when attempting to create directories that already existed (_affected mariadb connections_).
In addition to the above, a few test assertions where improved.
Sqlite, Postgresql and MariaDB were tested locally, before this PR was submitted. The reported issue #189 could not be confirmed for the following environment:
- PHP v8.2
- Laravel v11.8
- league/flysystem v3.28
* #189
=> Improve flysystem

packages/MimeTypes/src/Drivers/BaseSampler.php, tests/Integration/MimeTypes/DetectorTest.php, tests/_data/configs/mime-types/mime-types-detection.php
Fixes issue where a default sample size is not respected by Mime Type detector's sampler.
See #191 for details.
=> Fix mime type sample size

CHANGELOG.md, packages/Flysystem/Db/src/Adapters/DatabaseAdapter.php
Fixes #195 
The `DatabaseAdapter` failed to move or copy a file, if the source and destination where the same.
Now, the adapter simply skips attempting to move or copy a file, if the source and destination paths are the same.
=> Fix unable to read file

CHANGELOG.md, packages/Http/Api/src/Middleware/CaptureFieldsToSelect.php, tests/Integration/Http/Api/Middleware/CaptureFieldsToSelectMiddlewareTest.php
Fixes #197
The middlware is now able to accept string and array input. However, in case of other types, the middleware throws a HTTP "400 Bad Request" exception.
=> Fix "capture fields to select" middleware

CHANGELOG_v9x.md, packages/Utils/src/Json.php
`Json::isValid()` now uses PHP's native `json_validate()` for validating json strings. In addition, `$depth` and `$options` parameters are now supported by `isValid()`.
#120
=> Use json_validate() in Json::isValid()

CHANGELOG_v9x.md, composer.json
PR upgrades [PHPStan](https://phpstan.org/) to `v2.x`.
#200
=> Upgrade php stan to version 2.x

CHANGELOG_v9x.md, docs/archive/next/upgrade-guide.md, docs/archive/next/utils/array.md, docs/archive/next/utils/math.md, packages/Console/src/Commands/PirateTalkCommand.php, packages/Utils/src/Arr.php, packages/Utils/src/Math.php, tests/Unit/Utils/ArrTest.php, tests/Unit/Utils/MathTest.php
PR removed the following deprecated methods:
* `\Aedart\Utils\Arr::randomElement()`. _Replaced by `\Aedart\Utils\Arr::randomizer()->value()`_.
* `\Aedart\Utils\Math::randomInt()`. _Replaced by `\Aedart\Utils\Math::randomizer()->int()`_.
=> Remove deprecated methods

CHANGELOG_v9x.md, composer.json, docs/archive/next/http/clients/methods/expectations.md, packages/Http/Api/composer.json, packages/Http/Clients/composer.json
PR upgrades `shrikeh/teapot` to version `3.x`
Thought this could perhaps break something in the various packages - but lucky this didn't happen. It appears that `shrikeh/teapot` is fully backwards compatible with its `v2.x` series.
=> Upgrade http response status dependency

CHANGELOG_v9x.md, packages/Auth/composer.json, packages/Auth/src/Fortify/Exceptions/FailedLoginAttempt.php, packages/Auth/src/Fortify/Exceptions/PasswordResetLinkFailure.php, packages/Auth/src/Fortify/Responses/FailedPasswordResetLinkApiResponse.php, packages/Auth/src/Fortify/Responses/FailedPasswordResetLinkRequestResponse.php, tests/Integration/Auth/Fortify/FailedPasswordResetLinkApiResponseTest.php
PR added a few components in the auth package, to ensure that it does not remain entirely empty.
The following components are added (_extracted from an application_):
* `FailedLoginAttempt` validation exception.
* `PasswordResetLinkFailure` validation exception.
* `FailedPasswordResetLinkApiResponse` - custom implementation of Laravel Fortify's `FailedPasswordResetLinkRequestResponse`.
#202
=> Add auth components

.github/workflows/redmine_api_tests.yaml, CHANGELOG.md, docs/archive/current/redmine/README.md, packages/Redmine/src/CustomField.php, packages/Redmine/src/Enumeration.php, packages/Redmine/src/Issue.php, packages/Redmine/src/IssueStatus.php, packages/Redmine/src/Pagination/PaginatedResults.php, packages/Redmine/src/Partials/IssueStatusReference.php, packages/Redmine/src/RedmineApiResource.php, packages/Redmine/src/User.php, packages/Redmine/src/Version.php, tests/Integration/Redmine/Pagination/TraversableResultsTest.php, tests/Integration/Redmine/Relations/BelongsToRelationTest.php, tests/Integration/Redmine/Relations/Custom/AssignedToRelationTest.php, tests/Integration/Redmine/Relations/HasManyRelationTest.php, tests/Integration/Redmine/Relations/OneFromListRelationTest.php, tests/Integration/Redmine/Resources/CustomFieldTest.php, tests/Integration/Redmine/Resources/EnumerationResourcesTest.php, tests/Integration/Redmine/Resources/IssueCategoryTest.php, tests/Integration/Redmine/Resources/IssueNotesTest.php, tests/Integration/Redmine/Resources/IssueRelationsTest.php, tests/Integration/Redmine/Resources/IssueTest.php, tests/Integration/Redmine/Resources/ProjectMembershipTest.php, tests/Integration/Redmine/Resources/ProjectTest.php, tests/Integration/Redmine/Resources/VersionTest.php, tests/TestCases/Redmine/RedmineTestCase.php, tests/_data/configs/redmine/http-clients.php
PR attempts to enable automatic testing of the Redmine API Client. However, this has somewhat failed. A new workflow has been added, which now can be triggered manually. Sadly, it does not appear to work as intended - for reasons that are beyond my understanding.
Additionally, the Redmine package has "finally" been upgraded to support Redmine version `5.0.x` and `5.1.x`. A local Redmine instance has been used for this purpose. Mostly, only a few API Resources need to support one or more properties, in order for the client to be compatible with the newer API versions.
Even so, when testing manually, an sqlite3 database was used, which for some reason started to behave strange (_in Ruby_), yielding several "SQLite3: BusyException" errors (_mainly for Redmine version `5.1.x`_). This appears …
=> Improve redmine api testing

CHANGELOG.md, packages/Streams/src/Stream.php, packages/Streams/src/Transactions/Drivers/BaseTransactionDriver.php, tests/Helpers/Dummies/Properties/Accessibility/Person.php, tests/Unit/Properties/OverloadTest.php
PR fixes PHPStan error, in which a class property cannot be unset due to possible property hook in subclass, in PHP `v8.4`.
All the affected properties are now reset, e.g. set to `null` or other appropriate default value.
#226
=> Fix unset property check
